	[CLASS_NONE]                = {},
	
	[CLASS_EPHRAIM_LORD]        = {},
	[CLASS_EIRIKA_LORD]         = {},
	[CLASS_EPHRAIM_MASTER_LORD] = {},
	[CLASS_EIRIKA_MASTER_LORD]  = {},
	[CLASS_CAVALIER]            = {
		.rank_ride = WPN_EXP_E,
	},
	[CLASS_CAVALIER_F]          = {
		.rank_ride = WPN_EXP_E,
	},
	[CLASS_PALADIN]             = {},
	[CLASS_PALADIN_F]           = {},
	[CLASS_ARMOR_KNIGHT]        = {},
	[CLASS_ARMOR_KNIGHT_F]      = {},
	[CLASS_GENERAL]             = {},
	[CLASS_GENERAL_F]           = {},
	[CLASS_THIEF]               = {},
    [CLASS_MANAKETE]            = {},
	[CLASS_MERCENARY]           = {},
	[CLASS_MERCENARY_F]         = {},
	[CLASS_HERO]                = {},
	[CLASS_HERO_F]              = {},
	[CLASS_MYRMIDON]            = {},
	[CLASS_MYRMIDON_F]          = {},
	[CLASS_SWORDMASTER]         = {},
	[CLASS_SWORDMASTER_F]       = {},
	[CLASS_ASSASSIN]            = {},
	[CLASS_ASSASSIN_F]          = {},
	[CLASS_ARCHER]              = {},
	[CLASS_ARCHER_F]            = {},
	[CLASS_SNIPER]              = {},
	[CLASS_SNIPER_F]            = {},
	[CLASS_RANGER]              = {},
	[CLASS_RANGER_F]            = {},
	[CLASS_WYVERN_RIDER]        = {
		.rank_fly = WPN_EXP_E,
	},
	[CLASS_WYVERN_RIDER_F]      = {
		.rank_fly = WPN_EXP_E,
	},
	[CLASS_WYVERN_LORD]         = {
		.rank_fly = WPN_EXP_B,
	},
	[CLASS_WYVERN_LORD_F]       = {
		.rank_fly = WPN_EXP_B,
	},
	[CLASS_WYVERN_KNIGHT]       = {
		.rank_fly = WPN_EXP_B,
	},
	[CLASS_WYVERN_KNIGHT_F]     = {
		.rank_fly = WPN_EXP_B,
	},
	[CLASS_MAGE]                = {},
	[CLASS_MAGE_F]              = {},
	[CLASS_SAGE]                = {},
	[CLASS_SAGE_F]              = {},
	[CLASS_MAGE_KNIGHT]         = {},
	[CLASS_MAGE_KNIGHT_F]       = {},
	[CLASS_BISHOP]              = {},
	[CLASS_BISHOP_F]            = {},
	[CLASS_SHAMAN]              = {},
	[CLASS_SHAMAN_F]            = {},
	[CLASS_DRUID]               = {},
	[CLASS_DRUID_F]             = {},
	[CLASS_SUMMONER]            = {},
 	[CLASS_SUMMONER_F]          = {},
 	[CLASS_ROGUE]               = {},
 	[CLASS_GORGONEGG2]          = {},
 	[CLASS_GREAT_KNIGHT]        = {},
 	[CLASS_GREAT_KNIGHT_F]      = {},
 	[CLASS_RECRUIT_T1]          = {},
 	[CLASS_JOURNEYMAN_T2]       = {},
 	[CLASS_PUPIL_T2]            = {},
 	[CLASS_RECRUIT_T2]          = {},
 	[CLASS_MANAKETE_2]          = {},
 	[CLASS_MANAKETE_MYRRH]      = {},
 	[CLASS_JOURNEYMAN]          = {},
 	[CLASS_PUPIL]               = {},
 	[CLASS_FIGHTER]             = {},
 	[CLASS_WARRIOR]             = {},
 	[CLASS_BRIGAND]             = {},
 	[CLASS_PIRATE]              = {},
 	[CLASS_BERSERKER]           = {},
 	[CLASS_MONK]                = {},
 	[CLASS_PRIEST]              = {},
 	[CLASS_BARD]                = {},
 	[CLASS_RECRUIT]             = {},
 	[CLASS_PEGASUS_KNIGHT]      = {},
 	[CLASS_FALCON_KNIGHT]       = {},
 	[CLASS_CLERIC]              = {},
 	[CLASS_TROUBADOUR]          = {},
 	[CLASS_VALKYRIE]            = {},
 	[CLASS_DANCER]              = {},
 	[CLASS_SOLDIER]             = {},
 	[CLASS_NECROMANCER]         = {},
 	[CLASS_FLEET]               = {},
 	[CLASS_PHANTOM]             = {},
 	[CLASS_REVENANT]            = {},
 	[CLASS_ENTOUMBED]           = {},
 	[CLASS_BONEWALKER]          = {},
 	[CLASS_BONEWALKER_BOW]      = {},
 	[CLASS_WIGHT]               = {},
 	[CLASS_WIGHT_BOW]           = {},
 	[CLASS_BAEL]                = {},
 	[CLASS_ELDER_BAEL]          = {},
 	[CLASS_CYCLOPS]             = {},
 	[CLASS_MAUTHEDOOG]          = {},
 	[CLASS_GWYLLGI]             = {},
 	[CLASS_TARVOS]              = {},
 	[CLASS_MAELDUIN]            = {},
 	[CLASS_MOGALL]              = {},
 	[CLASS_ARCH_MOGALL]         = {},
 	[CLASS_GORGON]              = {},
 	[CLASS_GORGONEGG]           = {},
 	[CLASS_GARGOYLE]            = {},
 	[CLASS_DEATHGOYLE]          = {},
 	[CLASS_DRACO_ZOMBIE]        = {},
 	[CLASS_DEMON_KING]          = {},
 	[CLASS_BLST_REGULAR_USED]   = {},
 	[CLASS_BLST_LONG_USED]      = {},
 	[CLASS_BLST_KILLER_USED]    = {},
 	[CLASS_BLST_REGULAR_EMPTY]  = {},
 	[CLASS_BLST_LONG_EMPTY]     = {},
 	[CLASS_BLST_KILLER_EMPTY]   = {},
 	[CLASS_CIVILIAN_M1]         = {},
 	[CLASS_CIVILIAN_F1]         = {},
 	[CLASS_CIVILIAN_M2]         = {},
 	[CLASS_CIVILIAN_F2]         = {},
 	[CLASS_CIVILIAN_M3]         = {},
 	[CLASS_CIVILIAN_F3]         = {},
 	[CLASS_PEER]                = {},
 	[CLASS_QUEEN]               = {},
 	[CLASS_PRINCE]              = {},
 	[CLASS_QUEEN_2]             = {},
 	[CLASS_UNK78]               = {},
 	[CLASS_FALLEN_PRINCE]       = {},
 	[CLASS_TENT]                = {},
 	[CLASS_PONTIFEX]            = {},
 	[CLASS_FALLEN_PEER]         = {},
 	[CLASS_CYCLOPS_2]           = {},
 	[CLASS_ELDER_BAEL_2]        = {},
 	[CLASS_JOURNEYMAN_T1]       = {},
 	[CLASS_PUPIL_T1]            = {},
	
	
	
	
	
	
	
	
	
	
	
	
	
	[CHARACTER_NONE]         = {}, // 

    // Player Characters
	[CHARACTER_EIRIKA]       = {}, // 01,
	[CHARACTER_SETH]         = {}, // 02,
	[CHARACTER_GILLIAM]      = {}, // 03,
	[CHARACTER_FRANZ]        = {}, // 04,
	[CHARACTER_MOULDER]      = {}, // 05,
	[CHARACTER_VANESSA]      = {}, // 06,
	[CHARACTER_ROSS]         = {}, // 07,
	[CHARACTER_NEIMI]        = {}, // 08,
	[CHARACTER_COLM]         = {}, // 09,
	[CHARACTER_GARCIA]       = {}, // 0A,
	[CHARACTER_INNES]        = {}, // 0B,
	[CHARACTER_LUTE]         = {}, // 0C,
	[CHARACTER_NATASHA]      = {}, // 0D,
	[CHARACTER_CORMAG]       = {}, // 0E,
	[CHARACTER_EPHRAIM]      = {}, // 0F,
	[CHARACTER_FORDE]        = {}, // 10,
	[CHARACTER_KYLE]         = {}, // 11,
	[CHARACTER_AMELIA]       = {}, // 12,
	[CHARACTER_ARTUR]        = {}, // 13,
	[CHARACTER_GERIK]        = {}, // 14,
	[CHARACTER_TETHYS]       = {}, // 15,
	[CHARACTER_MARISA]       = {}, // 16,
	[CHARACTER_SALEH]        = {}, // 17,
	[CHARACTER_EWAN]         = {}, // 18,
	[CHARACTER_LARACHEL]     = {}, // 19,
	[CHARACTER_DOZLA]        = {}, // 1A,
	[CHARACTER_RENNAC]       = {}, // 1C,
	[CHARACTER_DUESSEL]      = {}, // 1D,
	[CHARACTER_MYRRH]        = {}, // 1E,
	[CHARACTER_KNOLL]        = {}, // 1F,
	[CHARACTER_JOSHUA]       = {}, // 20,
	[CHARACTER_SYRENE]       = {}, // 21,
	[CHARACTER_TANA]         = {}, // 22,
	[CHARACTER_LYON_CC]      = {}, // 23,
	[CHARACTER_ORSON_CC]     = {}, // 24,
	[CHARACTER_GLEN_CC]      = {}, // 25,
	[CHARACTER_SELENA_CC]    = {}, // 26,
	[CHARACTER_VALTER_CC]    = {}, // 27,
	[CHARACTER_RIEV_CC]      = {}, // 28,
	[CHARACTER_CAELLACH_CC]  = {}, // 29,
	[CHARACTER_FADO_CC]      = {}, // 2A,
	[CHARACTER_ISMAIRE_CC]   = {}, // 2B,
	[CHARACTER_HAYDEN_CC]    = {}, // 2C,

    // Summoned Characters
	[CHARACTER_SUMMON_LYON]  = {}, // 3B,
	[CHARACTER_SUMMON_KNOLL] = {}, // 3E,
	[CHARACTER_SUMMON_EWAN]  = {}, // 3F,

    // Boss/Unique Enemy Characters
	[CHARACTER_LYON]         = {}, // 40,
	[CHARACTER_MORVA]        = {}, // 41,
	[CHARACTER_ORSON_CH5X]   = {}, // 42,
	[CHARACTER_VALER]        = {}, // 43,
	[CHARACTER_SELENA]       = {}, // 44,
	[CHARACTER_VALTER_PROLOGUE] = {}, // 45,
	[CHARACTER_BREGUET]      = {}, // 46,
	[CHARACTER_BONE]         = {}, // 47,
	[CHARACTER_BAZBA]        = {}, // 48,
	[CHARACTER_ENTOUMBED_CH4] = {}, // 49,
	[CHARACTER_SAAR]         = {}, // 4A,
	[CHARACTER_NOVALA]       = {}, // 4B,
	[CHARACTER_MURRAY]       = {}, // 4C,
	[CHARACTER_TIRADO]       = {}, // 4D,
	[CHARACTER_BINKS]        = {}, // 4E,
	[CHARACTER_PABLO]        = {}, // 4F,
	[CHARACTER_MAELDUIN_CHUnk] = {}, // 50, // TODO: which chapter?
	[CHARACTER_AIAS]         = {}, // 51,
	[CHARACTER_CARLYLE]      = {}, // 52,
	[CHARACTER_CAELLACH]     = {}, // 53,
	[CHARACTER_PABLO_2]      = {}, // 54, // TODO: which chapter?
	[CHARACTER_GORGON_CHUnk] = {}, // 56, // TODO: which chapter?
	[CHARACTER_RIEV]         = {}, // 57,
	[CHARACTER_GHEB]         = {}, // 5A,
	[CHARACTER_BERAN]        = {}, // 5B,
	[CHARACTER_CYCLOPS_CHUnk] = {}, // 5C,
	[CHARACTER_WIGHT_CHUnk]  = {}, // 5D,
	[CHARACTER_DEATHGOYLE_CHUnk] = {}, // 5E,
	[CHARACTER_BANDIT_CH5]   = {}, // 66,
	[CHARACTER_ONEILL]       = {}, // 68,
	[CHARACTER_GLEN]         = {}, // 69,
	[CHARACTER_ZONTA]        = {}, // 6A,
	[CHARACTER_VIGARDE]      = {}, // 6B,
	[CHARACTER_LYON_FINAL]   = {}, // 6C,
	[CHARACTER_ORSON]	= {}, // 6D,

	[CHARACTER_FOMORTIIS]    = {}, // BE,

	[CHARACTER_WALL]         = {}, // FE,
	[CHARACTER_SNAG]         = {}, // FF,
	
	
	
	
	
	
	
	
	
	
